name: Auto Commit

on:
  schedule:
    # Runs every day at 1:00 AM UTC
    - cron: '0 1 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Configure Git user
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global i18n.commitEncoding utf-8
        git config --global i18n.logOutputEncoding utf-8

    # Modify the file and commit changes
    - name: Update content and commit
      run: |
        export LC_ALL=en_US.UTF-8
        export LANG=en_US.UTF-8
        export LANGUAGE=en_US.UTF-8
        echo "Adding content on $(date +"%Y-%m-%d %H:%M:%S")" | iconv -t UTF-8 >> content.txt
        git add content.txt
        git commit -m "Auto update with current date and time on $(date +"%Y-%m-%d %H:%M:%S")"

    # Push changes
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push origin HEAD:main
